[Eth]
NetworkId = 2147483647
SyncMode = "fast"
LightPeers = 100
DatabaseCache = 768
Etherbase = "0x174ad10186079347ce258add2e98b65498ca53ff"
MinerGasPrice = 18000000000
EnablePreimageRecording = false
Authash = true

[Eth.Ethash]
CacheDir = "ethash2"
CachesInMem = 2
CachesOnDisk = 3
DatasetDir = "./ethash2/.ethash"
DatasetsInMem = 1
DatasetsOnDisk = 2
PowMode = 0
BlockSignersContract = ""
AuthorizedSigners = ["0x8c2afeecfc769e1125b1d7d4be3f8753fc9b3bbd", "0x174ad10186079347ce258add2e98b65498ca53ff"]

[Eth.TxPool]
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01

[Node]
UserIdent = "ShyftTestnetNode"
DataDir = "shyftData2"
KeyStoreDir = "shyft-config/keystore" 
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
HTTPPort = 8549
HTTPCors = ["*"]
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth", "shh", "miner", "admin"]
WSPort = 8550
WSModules = ["net", "web3", "eth", "shh"]
WhisperSignersContract = "0xfAeCcaE8c1AF6bDFd71095E1B6a2F61C61C8a7E7"

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = []
BootstrapNodesV5 = []
StaticNodes = []
TrustedNodes = []
ListenAddr = ":31335"
EnableMsgEvents = false

[Dashboard]
Host = "localhost"
Port = 8080
Refresh = 5000000000
